# Reusable workflow to build a Phaser project within a folder

name: Build Phaser project

on:
  workflow_call:
    inputs:
      project_folder:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_folder }}
    steps:
    
      - uses: actions/checkout@v2
      
      - run: ls
           
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'
          cache: 'npm'

      - name: Build project 🔧
        run: | 
          npm install
          npm run build
