# Reusable workflow to build a Phaser project within a folder

name: CI CD Phaser project

on:
  workflow_call:
    inputs:
      project_folder:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_folder }}
    steps:
    
      - uses: actions/checkout@v2
                
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project_folder }}/package-lock.json

      - name: Build project 🔧
        run: | 
          npm install
          npm run build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{ inputs.project_folder }}/_build
          target-folder: ${{ inputs.project_folder }}
